#  "Data Cleaning for the Identification of Non-Paying Customers Eligible for Follow-Up Phone Outreach"

In [18]:
import pandas as pd 
import warnings 
df=pd.read_excel("Downloads/expanded_problematic_customer_call_list.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001.0,NaN,baggins,123.545.5421,"123 Shire Lane, Shire",Yess,no data,1.0
1,1002.0,Abed##,NADIR!!,123 643 9775,NaN,N,yess,0.0
2,1003.0,Walter##,/white**,Missing,298 Drugs Driveway,no,no data,NaN
3,1004.0,Dwight@@,NaN,(123)-543-2345,NaN,Yess,YES,1.0
4,1005.0,Jon##,SNOW!!,Missing,NaN,NaN,no data,1.0
5,1006.0,NaN,SWANSON,304-762-2467,NaN,Yess,yess,1.0
6,1007.0,Jeff,winger,Missing,1209 South Street???,N,n0,0.0
7,1008.0,Sherlock##,holmes**,876-678-34 69,98 Clue Drive,no,n0,0.0
8,1009.0,Gandalf@@,NaN,N/a,123 Middle Earth???,Yess,no data,0.0
9,1010.0,Peter,PARKER!!,123.545.5421,"25th Main Street, New York???",NaN,n0,NaN
10,1011.0,Samwise##,GAMGEE,Missing,"612 Shire Lane, Shire???",Yess,n0,1.0
11,1012.0,Harry@@,...POTTER**,7066950392,2394 Hogwarts Avenue???,Y,no data,1.0
12,1013.0,NaN,draper,Missing,NaN,Yess,n,0.0
13,1014.0,Leslie##,knope**,Missing,343 City Parkway,Yess,n0,0.0
14,1015.0,Toby##,FLENDERSON_,304-762-2467,NaN,no,n0,0.0
15,1016.0,Ron##,WEASLEY!!,123.545.5421,2395 Hogwarts Avenue???,NaN,n,0.0
16,1017.0,Michael ##,scott!!,123 643 9775,"121 Paper Avenue, Pennsylvania???",Yess,n0,0.0
17,1018.0,Clark,KENT,7066950392,3498 Super Lane???,Y,no data,1.0
18,1019.0,Creed##,BRATON,N/a,N/a???,N/a,yess,1.0
19,NaN,NaN,skywalker,876-678-34 69,"910 Tatooine Road, Tatooine",Yess,no data,1.0
20,1020.0,Anakin,skywalker,876-678-34 69,"910 Tatooine Road, Tatooine",Yess,n,NaN
21,1001.0,Frodo,NaN,123.545.5421,"123 Shire Lane, Shire",NaN,n0,1.0
22,1002.0,Abed##,nadir!!,123 643 9775,93 West Main Street???,N,yess,0.0
23,NaN,Walter@@,NaN,7066950392,298 Drugs Driveway???,NaN,no data,1.0
24,1004.0,NaN,NaN,(123)-543-2345,"980 Paper Avenue, Pennsylvania, 18503???",Yess,YES,1.0
25,1005.0,Jon,SNOW,Missing,123 Dragons Road,Y,no data,NaN
26,1006.0,NaN,swanson!!,304-762-2467,768 City Parkway,NaN,no data,1.0
27,1007.0,Jeff##,NaN,Missing,1209 South Street???,N,n0,0.0
28,1008.0,Sherlock,NaN,876-678-34 69,98 Clue Drive???,no,n0,NaN
29,NaN,Gandalf,NaN,N/a,123 Middle Earth,Yess,no data,NaN
30,NaN,Peter@@,PARKER**,Missing,"25th Main Street, New York",Yess,n0,1.0
31,NaN,Samwise@@,NaN,Missing,"612 Shire Lane, Shire",Yess,no data,1.0
32,1012.0,Harry,NaN,Missing,2394 Hogwarts Avenue,Y,no data,1.0
33,1013.0,Don@@,draper,(123)-543-2345,NaN,Yess,n,0.0
34,1014.0,Leslie@@,KNOPE!!,Missing,343 City Parkway,Yess,n0,0.0
35,1015.0,Toby,NaN,304-762-2467,NaN,no,n0,NaN
36,1016.0,Ron##,WEASLEY,123.545.5421,2395 Hogwarts Avenue,N,n,NaN
37,1017.0,Michael @@,NaN,123 643 9775,"121 Paper Avenue, Pennsylvania???",Yess,n0,0.0
38,1018.0,Clark##,NaN,7066950392,3498 Super Lane???,NaN,no data,1.0
39,1019.0,Creed@@,BRATON**,Missing,N/a???,N/a,no data,1.0
40,1020.0,Anakin,SKYWALKER!!,876-678-34 69,"910 Tatooine Road, Tatooine",Yess,n,1.0
41,1020.0,Anakin##,skywalker**,Missing,"910 Tatooine Road, Tatooine",Yess,n,1.0
42,NaN,Frodo@@,BAGGINS!!,123.545.5421,NaN,Yess,n0,1.0
43,1002.0,Abed,nadir!!,Missing,93 West Main Street,NaN,yess,0.0
44,1003.0,Walter@@,/WHITE,7066950392,298 Drugs Driveway,no,no data,1.0
45,NaN,Dwight,SCHRUTE**,(123)-543-2345,NaN,NaN,YES,1.0
46,1005.0,Jon##,snow,876-678-34 69,NaN,Y,n0,1.0
47,1006.0,Ron,swanson!!,304-762-2467,NaN,Yess,yess,1.0
48,1007.0,NaN,NaN,Missing,1209 South Street,N,n0,0.0
49,1008.0,NaN,HOLMES,876-678-34 69,98 Clue Drive???,no,n0,0.0
50,1009.0,Gandalf@@,NaN,N/a,123 Middle Earth,Yess,no data,0.0
51,NaN,Peter##,PARKER,Missing,"25th Main Street, New York",Yess,n0,1.0
52,1011.0,NaN,GAMGEE,Missing,NaN,Yess,n0,1.0
53,1012.0,Harry##,...potter,7066950392,2394 Hogwarts Avenue,Y,no data,1.0
54,NaN,Don##,DRAPER**,(123)-543-2345,2039 Main Street???,Yess,n,NaN
55,1014.0,Leslie@@,KNOPE**,876-678-34 69,343 City Parkway,NaN,n0,0.0
56,NaN,Toby@@,flenderson_!!,304-762-2467,214 HR Avenue???,NaN,n0,0.0
57,1016.0,Ron,WEASLEY!!,Missing,2395 Hogwarts Avenue???,N,no data,NaN
58,999999.0,Michael ##,NaN,123 643 9775,NaN,Yess,no data,NaN
59,1018.0,NaN,KENT**,Missing,3498 Super Lane,NaN,no data,1.0
60,1019.0,NaN,BRATON!!,Missing,N/a,NaN,yess,1.0
61,999999.0,Anakin##,skywalker**,876-678-34 69,"910 Tatooine Road, Tatooine",Yess,no data,1.0
62,1020.0,NaN,NaN,Missing,NaN,Yess,n,1.0
63,NaN,Frodo,baggins**,123.545.5421,"123 Shire Lane, Shire???",Yess,n0,1.0
64,1002.0,Abed,NADIR,123 643 9775,93 West Main Street,N,yess,0.0
65,1003.0,Walter##,/WHITE**,7066950392,298 Drugs Driveway,no,no data,1.0
66,NaN,Dwight##,SCHRUTE**,(123)-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yess,YES,1.0
67,1005.0,Jon@@,SNOW!!,876-678-34 69,NaN,Y,n0,1.0
68,1006.0,Ron##,SWANSON**,Missing,768 City Parkway,Yess,yess,1.0
69,1007.0,Jeff,NaN,Missing,1209 South Street,N,n0,0.0
70,1008.0,Sherlock##,NaN,876-678-34 69,98 Clue Drive???,NaN,n0,0.0
71,1009.0,Gandalf##,NaN,N/a,123 Middle Earth???,Yess,no data,0.0
72,999999.0,NaN,parker,Missing,"25th Main Street, New York???",Yess,n0,1.0
73,1011.0,Samwise,NaN,Missing,"612 Shire Lane, Shire???",NaN,n0,1.0
74,1012.0,Harry,...POTTER,Missing,2394 Hogwarts Avenue,Y,no data,NaN
75,1013.0,Don@@,DRAPER**,(123)-543-2345,2039 Main Street,Yess,n,0.0
76,1014.0,Leslie,NaN,876-678-34 69,NaN,Yess,n0,0.0
77,1015.0,NaN,FLENDERSON_**,304-762-2467,214 HR Avenue,no,n0,0.0
78,1016.0,Ron@@,weasley**,123.545.5421,2395 Hogwarts Avenue,N,n,0.0
79,1017.0,Michael ##,NaN,Missing,"121 Paper Avenue, Pennsylvania",Yess,n0,0.0
80,NaN,Clark##,kent**,Missing,3498 Super Lane???,NaN,no data,1.0
81,1019.0,Creed,braton,N/a,N/a,N/a,no data,1.0
82,1020.0,NaN,skywalker,876-678-34 69,"910 Tatooine Road, Tatooine",Yess,n,1.0
83,1020.0,Anakin##,SKYWALKER,Missing,"910 Tatooine Road, Tatooine???",Yess,n,1.0
84,1001.0,NaN,BAGGINS,123.545.5421,"123 Shire Lane, Shire",NaN,n0,1.0
85,1002.0,Abed@@,NaN,Missing,93 West Main Street???,N,no data,0.0
86,1003.0,Walter##,NaN,7066950392,298 Drugs Driveway,no,no data,1.0
87,NaN,Dwight,schrute!!,(123)-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yess,no data,NaN
88,1005.0,Jon@@,SNOW,876-678-34 69,NaN,Y,no data,1.0
89,1006.0,Ron@@,swanson,304-762-2467,NaN,Yess,yess,NaN
90,1007.0,Jeff@@,WINGER**,Missing,1209 South Street,N,n0,0.0
91,-1.0,NaN,HOLMES**,876-678-34 69,98 Clue Drive,no,n0,0.0
92,1009.0,Gandalf##,NaN,N/a,NaN,Yess,no data,0.0
93,1010.0,Peter,PARKER,123.545.5421,"25th Main Street, New York",Yess,no data,1.0
94,1011.0,NaN,gamgee**,Missing,"612 Shire Lane, Shire",Yess,n0,1.0
95,1012.0,Harry,...potter**,7066950392,NaN,Y,no data,1.0
96,1013.0,Don@@,NaN,(123)-543-2345,2039 Main Street???,Yess,n,0.0
97,1014.0,Leslie@@,knope,876-678-34 69,343 City Parkway,Yess,no data,0.0
98,1015.0,NaN,flenderson_,304-762-2467,214 HR Avenue???,no,n0,0.0
99,1016.0,Ron,WEASLEY!!,123.545.5421,2395 Hogwarts Avenue,N,n,NaN
100,-1.0,Michael ##,SCOTT!!,123 643 9775,NaN,Yess,no data,NaN
101,1018.0,NaN,kent,7066950392,3498 Super Lane,NaN,no data,1.0
102,1019.0,Creed@@,braton,N/a,N/a,N/a,yess,NaN
103,1020.0,Anakin@@,NaN,876-678-34 69,"910 Tatooine Road, Tatooine",Yess,n,NaN
104,1020.0,NaN,skywalker,876-678-34 69,NaN,Yess,n,1.0
105,999999.0,Frodo@@,NaN,123.545.5421,"123 Shire Lane, Shire???",Yess,no data,1.0
106,NaN,Abed,nadir!!,123 643 9775,NaN,NaN,yess,NaN
107,1003.0,Walter,/white!!,Missing,298 Drugs Driveway,no,no data,1.0
108,1004.0,Dwight,SCHRUTE!!,(123)-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yess,no data,1.0
109,NaN,Jon@@,SNOW**,876-678-34 69,NaN,Y,n0,1.0
110,1006.0,NaN,swanson**,304-762-2467,NaN,Yess,yess,1.0
111,1007.0,Jeff##,WINGER!!,Missing,1209 South Street???,N,n0,0.0
112,NaN,Sherlock##,HOLMES**,876-678-34 69,98 Clue Drive,NaN,n0,0.0
113,NaN,Gandalf##,NaN,N/a,123 Middle Earth,NaN,no data,NaN
114,1010.0,Peter,PARKER!!,123.545.5421,NaN,Yess,n0,1.0
115,1011.0,Samwise@@,gamgee!!,Missing,"612 Shire Lane, Shire???",Yess,n0,NaN
116,1012.0,NaN,NaN,Missing,2394 Hogwarts Avenue???,Y,no data,1.0
117,1013.0,Don@@,draper,(123)-543-2345,2039 Main Street,Yess,n,NaN
118,1014.0,Leslie##,NaN,876-678-34 69,343 City Parkway,Yess,n0,0.0
119,1015.0,Toby##,flenderson_**,304-762-2467,214 HR Avenue,no,n0,0.0
120,1016.0,NaN,weasley**,123.545.5421,2395 Hogwarts Avenue???,N,n,0.0
121,1017.0,Michael ##,SCOTT**,123 643 9775,"121 Paper Avenue, Pennsylvania???",Yess,no data,NaN
122,NaN,NaN,kent**,7066950392,3498 Super Lane,NaN,no data,1.0
123,1019.0,Creed,BRATON**,Missing,N/a???,N/a,yess,1.0
124,999999.0,Anakin##,skywalker!!,876-678-34 69,"910 Tatooine Road, Tatooine",Yess,n,NaN
125,NaN,Anakin##,SKYWALKER**,Missing,"910 Tatooine Road, Tatooine???",NaN,n,1.0
126,1001.0,NaN,BAGGINS**,123.545.5421,"123 Shire Lane, Shire",Yess,n0,NaN
127,1002.0,Abed,NADIR**,123 643 9775,93 West Main Street???,N,yess,0.0
128,1003.0,Walter@@,/WHITE!!,7066950392,298 Drugs Driveway???,no,no data,1.0
129,1004.0,NaN,NaN,(123)-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yess,YES,1.0
130,1005.0,Jon@@,snow**,876-678-34 69,NaN,Y,no data,1.0
131,1006.0,Ron##,SWANSON,304-762-2467,768 City Parkway???,Yess,yess,1.0
132,1007.0,Jeff##,WINGER**,Missing,NaN,N,n0,0.0
133,NaN,Sherlock##,HOLMES**,Missing,98 Clue Drive,NaN,n0,NaN
134,NaN,Gandalf,NaN,Missing,123 Middle Earth,Yess,no data,0.0
135,1010.0,NaN,NaN,123.545.5421,"25th Main Street, New York",NaN,n0,1.0
136,1011.0,Samwise##,GAMGEE!!,Missing,"612 Shire Lane, Shire",NaN,n0,1.0
137,NaN,Harry##,...POTTER!!,7066950392,2394 Hogwarts Avenue???,Y,no data,1.0
138,1013.0,Don@@,NaN,Missing,NaN,Yess,n,0.0
139,1014.0,Leslie@@,KNOPE**,Missing,343 City Parkway,Yess,n0,0.0
140,1015.0,Toby##,flenderson_,304-762-2467,214 HR Avenue,no,n0,0.0
141,1016.0,Ron,NaN,123.545.5421,2395 Hogwarts Avenue???,N,no data,0.0
142,1017.0,Michael,scott,123 643 9775,NaN,Yess,n0,NaN
143,1018.0,Clark##,kent,Missing,3498 Super Lane???,Y,no data,1.0
144,NaN,Creed,NaN,N/a,N/a,N/a,yess,1.0
145,1020.0,NaN,NaN,876-678-34 69,"910 Tatooine Road, Tatooine???",NaN,n,1.0
146,1020.0,Anakin@@,SKYWALKER,Missing,"910 Tatooine Road, Tatooine",NaN,no data,NaN
147,1001.0,Frodo,baggins**,123.545.5421,"123 Shire Lane, Shire",NaN,no data,NaN
148,1002.0,Abed,nadir!!,Missing,NaN,N,no data,0.0
149,1003.0,NaN,/WHITE,Missing,298 Drugs Driveway???,NaN,no data,1.0
150,NaN,Dwight##,NaN,(123)-543-2345,NaN,Yess,YES,1.0
151,1005.0,Jon,SNOW!!,876-678-34 69,123 Dragons Road???,Y,n0,NaN
152,NaN,Ron,swanson**,Missing,768 City Parkway???,Yess,yess,1.0
153,1007.0,Jeff##,winger!!,Missing,1209 South Street,NaN,n0,0.0
154,NaN,Sherlock,HOLMES**,876-678-34 69,98 Clue Drive,no,n0,0.0
155,1009.0,Gandalf@@,NaN,N/a,NaN,Yess,no data,0.0
156,1010.0,Peter@@,PARKER,123.545.5421,"25th Main Street, New York",Yess,n0,1.0
157,1011.0,Samwise@@,NaN,Missing,"612 Shire Lane, Shire???",Yess,n0,1.0
158,1012.0,Harry##,...POTTER**,7066950392,2394 Hogwarts Avenue,Y,no data,1.0
159,1013.0,NaN,DRAPER**,(123)-543-2345,2039 Main Street,Yess,n,NaN
160,-1.0,Leslie,KNOPE!!,876-678-34 69,NaN,Yess,n0,NaN
161,NaN,Toby,flenderson_!!,304-762-2467,214 HR Avenue,no,no data,0.0
162,NaN,Ron,WEASLEY**,123.545.5421,2395 Hogwarts Avenue,N,n,NaN
163,NaN,Michael,SCOTT,123 643 9775,"121 Paper Avenue, Pennsylvania",Yess,no data,0.0
164,1018.0,Clark@@,NaN,7066950392,3498 Super Lane,Y,no data,1.0
165,-1.0,Creed,BRATON,N/a,N/a,N/a,yess,1.0
166,1020.0,Anakin##,SKYWALKER**,876-678-34 69,"910 Tatooine Road, Tatooine",Yess,n,1.0
167,1020.0,Anakin,skywalker**,876-678-34 69,"910 Tatooine Road, Tatooine",Yess,n,1.0
168,1001.0,Frodo##,baggins!!,123.545.5421,"123 Shire Lane, Shire",Yess,no data,1.0
169,1002.0,Abed##,NADIR,123 643 9775,93 West Main Street,N,yess,NaN
170,1003.0,Walter@@,NaN,7066950392,NaN,no,no data,1.0
171,1004.0,NaN,SCHRUTE!!,(123)-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yess,YES,1.0
172,1005.0,Jon,SNOW**,876-678-34 69,NaN,Y,n0,1.0
173,1006.0,NaN,SWANSON,304-762-2467,768 City Parkway,Yess,yess,NaN
174,1007.0,NaN,winger**,Missing,1209 South Street???,N,n0,0.0
175,1008.0,Sherlock,HOLMES!!,876-678-34 69,98 Clue Drive,no,n0,0.0
176,1009.0,NaN,NaN,N/a,NaN,Yess,no data,NaN
177,1010.0,Peter,NaN,123.545.5421,"25th Main Street, New York",Yess,n0,1.0
178,1011.0,NaN,GAMGEE**,Missing,"612 Shire Lane, Shire",Yess,n0,1.0
179,1012.0,NaN,...POTTER!!,7066950392,2394 Hogwarts Avenue,Y,no data,1.0
180,-1.0,Don##,DRAPER,(123)-543-2345,2039 Main Street,Yess,n,0.0
181,1014.0,Leslie,KNOPE**,876-678-34 69,343 City Parkway,Yess,n0,NaN
182,1015.0,Toby@@,FLENDERSON_!!,304-762-2467,NaN,no,n0,0.0
183,1016.0,Ron##,WEASLEY**,123.545.5421,2395 Hogwarts Avenue,N,no data,0.0
184,NaN,Michael ##,NaN,123 643 9775,"121 Paper Avenue, Pennsylvania",Yess,no data,0.0
185,NaN,Clark@@,kent,Missing,3498 Super Lane,Y,no data,1.0
186,NaN,Creed@@,BRATON**,N/a,N/a,N/a,yess,1.0
187,1020.0,Anakin##,skywalker!!,876-678-34 69,"910 Tatooine Road, Tatooine???",Yess,n,1.0
188,1020.0,NaN,skywalker,876-678-34 69,"910 Tatooine Road, Tatooine",NaN,n,NaN
189,NaN,Frodo##,baggins!!,123.545.5421,"123 Shire Lane, Shire",Yess,no data,NaN
190,1002.0,Abed@@,nadir,123 643 9775,93 West Main Street,NaN,yess,0.0
191,NaN,Walter@@,NaN,7066950392,298 Drugs Driveway???,NaN,no data,1.0
192,1004.0,Dwight,SCHRUTE,(123)-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yess,YES,1.0
193,NaN,NaN,snow!!,876-678-34 69,NaN,NaN,n0,NaN
194,1006.0,Ron@@,SWANSON**,304-762-2467,768 City Parkway???,NaN,yess,1.0
195,1007.0,Jeff@@,winger,Missing,1209 South Street???,N,n0,0.0
196,NaN,Sherlock@@,holmes!!,876-678-34 69,98 Clue Drive,NaN,n0,NaN
197,NaN,Gandalf,NaN,N/a,123 Middle Earth,Yess,no data,0.0
198,NaN,Peter##,PARKER!!,123.545.5421,"25th Main Street, New York",Yess,n0,1.0
199,1011.0,Samwise##,NaN,Missing,NaN,NaN,no data,1.0
200,1012.0,Harry@@,...POTTER**,7066950392,2394 Hogwarts Avenue,Y,no data,1.0
201,1013.0,NaN,DRAPER**,(123)-543-2345,2039 Main Street,Yess,n,0.0
202,1014.0,NaN,NaN,Missing,343 City Parkway,Yess,n0,0.0
203,1015.0,Toby##,FLENDERSON_,Missing,214 HR Avenue,no,n0,NaN
204,1016.0,Ron##,weasley!!,123.545.5421,2395 Hogwarts Avenue???,NaN,n,0.0
205,1017.0,NaN,SCOTT,123 643 9775,NaN,Yess,n0,0.0
206,1018.0,Clark@@,KENT!!,7066950392,3498 Super Lane,NaN,no data,1.0
207,1019.0,Creed##,BRATON**,Missing,N/a,NaN,no data,1.0
208,1020.0,Anakin##,skywalker,876-678-34 69,"910 Tatooine Road, Tatooine???",Yess,n,1.0
209,1020.0,Anakin##,NaN,876-678-34 69,"910 Tatooine Road, Tatooine",NaN,n,1.0

In [19]:
warnings.filterwarnings("ignore")
pd.set_option("display.max_rows",None)

In [ ]:
df.info()

In [20]:
df=df.drop(columns=["Not_Useful_Column"])

In [23]:
df=df.drop_duplicates(subset=["CustomerID"])

In [27]:
df=df[df["CustomerID"].astype(str).str.len()==6]

In [29]:
df["CustomerID"]=df["CustomerID"].astype("int")

In [30]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,NaN,baggins,123.545.5421,"123 Shire Lane, Shire",Yess,no data
1,1002,Abed##,NADIR!!,123 643 9775,NaN,N,yess
2,1003,Walter##,/white**,Missing,298 Drugs Driveway,no,no data
3,1004,Dwight@@,NaN,(123)-543-2345,NaN,Yess,YES
4,1005,Jon##,SNOW!!,Missing,NaN,NaN,no data
5,1006,NaN,SWANSON,304-762-2467,NaN,Yess,yess
6,1007,Jeff,winger,Missing,1209 South Street???,N,n0
7,1008,Sherlock##,holmes**,876-678-34 69,98 Clue Drive,no,n0
8,1009,Gandalf@@,NaN,N/a,123 Middle Earth???,Yess,no data
9,1010,Peter,PARKER!!,123.545.5421,"25th Main Street, New York???",NaN,n0
10,1011,Samwise##,GAMGEE,Missing,"612 Shire Lane, Shire???",Yess,n0
11,1012,Harry@@,...POTTER**,7066950392,2394 Hogwarts Avenue???,Y,no data
12,1013,NaN,draper,Missing,NaN,Yess,n
13,1014,Leslie##,knope**,Missing,343 City Parkway,Yess,n0
14,1015,Toby##,FLENDERSON_,304-762-2467,NaN,no,n0
15,1016,Ron##,WEASLEY!!,123.545.5421,2395 Hogwarts Avenue???,NaN,n
16,1017,Michael ##,scott!!,123 643 9775,"121 Paper Avenue, Pennsylvania???",Yess,n0
17,1018,Clark,KENT,7066950392,3498 Super Lane???,Y,no data
18,1019,Creed##,BRATON,N/a,N/a???,N/a,yess
20,1020,Anakin,skywalker,876-678-34 69,"910 Tatooine Road, Tatooine",Yess,n

In [32]:
df["First_Name"]=df["First_Name"].fillna("Unknown").str.replace(r'[^a-zA-Z]','',regex=True)

In [34]:
df["Last_Name"]=df["Last_Name"].fillna("Unknown").str.replace(r'[^a-zA-Z]','',regex=True)

In [35]:
df["Last_Name"]=df["Last_Name"].str.capitalize()

In [36]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Unknown,Baggins,123.545.5421,"123 Shire Lane, Shire",Yess,no data
1,1002,Abed,Nadir,123 643 9775,NaN,N,yess
2,1003,Walter,White,Missing,298 Drugs Driveway,no,no data
3,1004,Dwight,Unknown,(123)-543-2345,NaN,Yess,YES
4,1005,Jon,Snow,Missing,NaN,NaN,no data
5,1006,Unknown,Swanson,304-762-2467,NaN,Yess,yess
6,1007,Jeff,Winger,Missing,1209 South Street???,N,n0
7,1008,Sherlock,Holmes,876-678-34 69,98 Clue Drive,no,n0
8,1009,Gandalf,Unknown,N/a,123 Middle Earth???,Yess,no data
9,1010,Peter,Parker,123.545.5421,"25th Main Street, New York???",NaN,n0
10,1011,Samwise,Gamgee,Missing,"612 Shire Lane, Shire???",Yess,n0
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue???,Y,no data
12,1013,Unknown,Draper,Missing,NaN,Yess,n
13,1014,Leslie,Knope,Missing,343 City Parkway,Yess,n0
14,1015,Toby,Flenderson,304-762-2467,NaN,no,n0
15,1016,Ron,Weasley,123.545.5421,2395 Hogwarts Avenue???,NaN,n
16,1017,Michael,Scott,123 643 9775,"121 Paper Avenue, Pennsylvania???",Yess,n0
17,1018,Clark,Kent,7066950392,3498 Super Lane???,Y,no data
18,1019,Creed,Braton,N/a,N/a???,N/a,yess
20,1020,Anakin,Skywalker,876-678-34 69,"910 Tatooine Road, Tatooine",Yess,n

In [38]:
df=df[(df["Phone_Number"]!="Missing") & (df["Phone_Number"]!="N/a")]

In [40]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Unknown,Baggins,123.545.5421,"123 Shire Lane, Shire",Yess,no data
1,1002,Abed,Nadir,123 643 9775,NaN,N,yess
3,1004,Dwight,Unknown,(123)-543-2345,NaN,Yess,YES
5,1006,Unknown,Swanson,304-762-2467,NaN,Yess,yess
7,1008,Sherlock,Holmes,876-678-34 69,98 Clue Drive,no,n0
9,1010,Peter,Parker,123.545.5421,"25th Main Street, New York???",NaN,n0
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue???,Y,no data
14,1015,Toby,Flenderson,304-762-2467,NaN,no,n0
15,1016,Ron,Weasley,123.545.5421,2395 Hogwarts Avenue???,NaN,n
16,1017,Michael,Scott,123 643 9775,"121 Paper Avenue, Pennsylvania???",Yess,n0
17,1018,Clark,Kent,7066950392,3498 Super Lane???,Y,no data
20,1020,Anakin,Skywalker,876-678-34 69,"910 Tatooine Road, Tatooine",Yess,n

In [47]:
df["Phone_Number"]=df['Phone_Number'].astype(str).str.replace(r'\D', '', regex=True)

In [50]:
df["Phone_Number"]=df["Phone_Number"].apply(lambda x: x[:3] +"-"+x[3:6]+"-"+x[6:10])

In [51]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Unknown,Baggins,123-545-5421,"123 Shire Lane, Shire",Yess,no data
1,1002,Abed,Nadir,123-643-9775,NaN,N,yess
3,1004,Dwight,Unknown,123-543-2345,NaN,Yess,YES
5,1006,Unknown,Swanson,304-762-2467,NaN,Yess,yess
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,no,n0
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York???",NaN,n0
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue???,Y,no data
14,1015,Toby,Flenderson,304-762-2467,NaN,no,n0
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue???,NaN,n
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania???",Yess,n0
17,1018,Clark,Kent,706-695-0392,3498 Super Lane???,Y,no data
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yess,n

In [58]:
df["Paying Customer"]=df["Paying Customer"].replace("Yess","Yes")

In [68]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Unknown,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,no data
1,1002,Abed,Nadir,123-643-9775,NaN,N,yess
3,1004,Dwight,Unknown,123-543-2345,NaN,Yes,YES
5,1006,Unknown,Swanson,304-762-2467,NaN,Yes,yess
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,no,n0
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York???",NaN,n0
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue???,Y,no data
14,1015,Toby,Flenderson,304-762-2467,NaN,no,n0
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue???,NaN,n
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania???",Yes,n0
17,1018,Clark,Kent,706-695-0392,3498 Super Lane???,Y,no data
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,n

In [71]:
df["Paying Customer"]=df["Paying Customer"].str.strip()

In [73]:
df["Paying Customer"]=df["Paying Customer"].replace("Y","Yes")

In [74]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Unknown,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,no data
1,1002,Abed,Nadir,123-643-9775,NaN,N,yess
3,1004,Dwight,Unknown,123-543-2345,NaN,Yes,YES
5,1006,Unknown,Swanson,304-762-2467,NaN,Yes,yess
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,no,n0
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York???",NaN,n0
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue???,Yes,no data
14,1015,Toby,Flenderson,304-762-2467,NaN,no,n0
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue???,NaN,n
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania???",Yes,n0
17,1018,Clark,Kent,706-695-0392,3498 Super Lane???,Yes,no data
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,n

In [77]:
df["Paying Customer"]=df["Paying Customer"].replace("no","No")
df["Paying Customer"]=df["Paying Customer"].replace("N","No")
df["Paying Customer"]=df["Paying Customer"].fillna('')

In [78]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Unknown,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,no data
1,1002,Abed,Nadir,123-643-9775,NaN,No,yess
3,1004,Dwight,Unknown,123-543-2345,NaN,Yes,YES
5,1006,Unknown,Swanson,304-762-2467,NaN,Yes,yess
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,No,n0
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York???",,n0
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue???,Yes,no data
14,1015,Toby,Flenderson,304-762-2467,NaN,No,n0
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue???,,n
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania???",Yes,n0
17,1018,Clark,Kent,706-695-0392,3498 Super Lane???,Yes,no data
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,n

In [80]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.strip()

In [81]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].replace("nO","No")
df["Do_Not_Contact"]=df["Do_Not_Contact"].replace("n","No")
df["Do_Not_Contact"]=df["Do_Not_Contact"].replace("yess","Yes")

In [84]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].replace("n0","No")

In [85]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Unknown,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,no data
1,1002,Abed,Nadir,123-643-9775,NaN,No,Yes
3,1004,Dwight,Unknown,123-543-2345,NaN,Yes,YES
5,1006,Unknown,Swanson,304-762-2467,NaN,Yes,Yes
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,No,No
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York???",,No
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue???,Yes,no data
14,1015,Toby,Flenderson,304-762-2467,NaN,No,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue???,,No
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania???",Yes,No
17,1018,Clark,Kent,706-695-0392,3498 Super Lane???,Yes,no data
20,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,No

In [87]:
df=df[df["Do_Not_Contact"]=="No"]

In [91]:
df=df[df["Paying Customer"]=="No"]

In [92]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,No,No
14,1015,Toby,Flenderson,304-762-2467,NaN,No,No

In [94]:
df["Address"]=df["Address"].fillna('')

In [98]:
df.reset_index(drop=True,inplace=True)

In [99]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,No,No
1,1015,Toby,Flenderson,304-762-2467,,No,No